---
# mirsg.infrastructure.install_python
install_python:
  version: "3"
  pip_version: 21.2.3
  pip_executable: /usr/bin/pip3
  system_packages:
    - python3
    - python3-pip
    - python3-setuptools
    - python3-libselinux
    - policycoreutils-python-utils
  pip_packages:
    - cryptography
    - gunicorn
    - flask

gunicorn_executable: /usr/local/bin/gunicorn
