---
# mirsg.infrastructure.firewalld
firewalld_allow_public_access: true

firewalld_public_zone_sources:
  - "0.0.0.0/0"

firewalld_internal_zone_ports:
  - "{{ nginx_upstream_listen_port }}"

firewalld_work_zone_ports:
  - "{{ nginx_upstream_listen_port }}"

firewalld_public_zone_ports:
  - "{{ nginx_upstream_listen_port }}"

# mirsg.xnat.xnat
# Some times the default admin account hasn't finished creating even after tomcat has started
# Add a delay here to give the admin account a chance to be created
# Note, this issue only seems to happen in CI
xnat_wait_for_tomcat: 15

# nginx config
nginx_diffie_helman_size_bits: 2048
nginx_conf_template: nginx_reverse_proxy_as_default.j2
